
spring:
  datasource:
    url: jdbc:h2:mem:cubdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
server:
  port: 8080

coindesk:
  url: https://api.coindesk.com/v1/bpi/currentprice.json
  # fallback mock (from assignment)
  mock: |
    {
      "time": {"updated": "Aug 3, 2022 20:25:00 UTC","updatedISO": "2022-08-03T20:25:00+00:00","updateduk": "Aug 3, 2022 at 21:25 BST"},
      "disclaimer": "Mocked from assignment",
      "chartName": "Bitcoin",
      "bpi": {
        "USD": {"code": "USD","symbol": "$","rate": "23,342.0112","description": "US Dollar","rate_float": 23342.0112},
        "GBP": {"code": "GBP","symbol": "£","rate": "19,504.3978","description": "British Pound Sterling","rate_float": 19504.3978},
        "EUR": {"code": "EUR","symbol": "€","rate": "22,738.5269","description": "Euro","rate_float": 22738.5269}
      }
    }
management:
  endpoints:
    web:
      exposure:
        include: health,info
